### ISSUE TITLE
criar design da tela de calendário e lembretes

### ISSUE THREAD

**Issue by follijulio** [RitadeCassiabl/Projeto_Luci#4]

**Comment by RitadeCassiabl** [comment]
Design
![image](https://github.com/user-attachments/assets/7649b6b2-ae2b-4744-8ba1-bc4e6f56ba80)
![image](https://github.com/user-attachments/assets/d22ef651-2f79-4c2c-a635-8899afc1f0ca)
![image](https://github.com/user-attachments/assets/e6fd6c60-17a5-4b12-b97f-7e5127f68e05)
![image](https://github.com/user-attachments/assets/b5242f6e-4609-44fb-978c-91df3967523d)
